name: Multi platform build

on:
  push:
    branches:
      - "my-changes"
  
  workflow_dispatch:

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install required libraries
        run: |
          sudo apt update
          sudo apt install -y make qmake6 qt6-base-dev qt6-core

      - name: Build
        run: |
            mkdir build
            cd build
            qmake6 ../ImageCorrupter.pro
            make



